# Generated by Django 5.2 on 2025-04-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Koulutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oppilaitos', models.CharField(max_length=100)),
                ('tutkinto', models.CharField(max_length=100)),
                ('kuvaus', models.TextField()),
                ('aloitusvuosi', models.DateField()),
                ('valmistumisvuosi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Taidot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taido', models.CharField(max_length=100)),
                ('taso', models.IntegerField(choices=[(1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')])),
            ],
        ),
        migrations.CreateModel(
            name='TietojaMinusta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otsikko', models.CharField(max_length=100)),
                ('kuvaus', models.TextField()),
                ('kuva', models.ImageField(upload_to='kuvat/')),
            ],
        ),
        migrations.CreateModel(
            name='Tyokokemus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yritys', models.CharField(max_length=100)),
                ('tehtava', models.CharField(max_length=100)),
                ('kuvaus', models.TextField()),
                ('alkupvm', models.DateField()),
                ('loppupvm', models.DateField()),
            ],
        ),
    ]
